REPLICATE_API_TOKEN = "r8_b9UXgQgcaVhvOodIeOrs1qftIMmMEkl3jDojS"

OPENAI_API_KEY = "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"
